steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build docker image'
    args: 
      - 'build'
      - '-t'
      - 'us-east1-docker.pkg.dev/k8s-b00930528/cloud-k8/container-2:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push image to AR'
    args:
      - 'push'
      - 'us-east1-docker.pkg.dev/k8s-b00930528/cloud-k8/container-2:latest'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'GCR credentials'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'my-cluster'
      - '--zone'
      - 'us-central1-a'

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Deploy to GKE Cluster'
    env: 
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'
    args:
      - 'apply' 
      - '-f'
      - 'container2-deployment.yaml,container2-service.yaml'

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Refresh Pods'
    env:
      - CLOUDSDK_COMPUTE_ZONE=us-central1-a
      - CLOUDSDK_CONTAINER_CLUSTER=my-cluster
    args:
      - delete
      - pods
      - '--all'