apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-2
  template:
    metadata:
      labels:
        app: container-2
    spec:
      containers:
        - name: container-2
          image: us-east1-docker.pkg.dev/k8s-b00930528/cloud-k8/container-2:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: alen-pv-dir
              mountPath: /alen_PV_dir
      volumes:
        - name: alen-pv-dir
          persistentVolumeClaim:
            claimName: alen-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alen-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi